services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
    command: bash -c "find bin/ -type f | xargs sed -i 's/\r$//' && bundle install && bundle exec rails db:prepare db:seed && bundle exec rails tailwindcss:build && bundle exec rails server -b 0.0.0.0"

volumes:
  bundle_cache:
